import { GoogleGenAI, Type } from '@google/genai';
import { BenchmarkInputs, ScopeAndBenchmarks, MatrixResult, SynthesisResult } from '../types';

const getModelName = (): string => {
  if (typeof window !== 'undefined') {
    const savedModel = localStorage.getItem('GEMINI_MODEL_NAME');
    if (savedModel && savedModel.trim().length > 0) {
      return savedModel.trim();
    }
  }
  return 'gemini-flash-latest';
};

const getAIClient = (): GoogleGenAI => {
  const savedKey = typeof window !== 'undefined' ? localStorage.getItem('GEMINI_API_KEY') : null;
  if (savedKey && savedKey.trim().length > 0) {
    // Google AI Studio Direct Mode (Browser-compatible, client-side direct execution)
    return new GoogleGenAI({ apiKey: savedKey.trim() });
  }
  if (process.env.API_KEY && process.env.API_KEY.trim().length > 0) {
    return new GoogleGenAI({ apiKey: process.env.API_KEY.trim() });
  }
  throw new Error("API Key missing. Please enter a valid Google AI Studio API Key in the top configuration field.");
};

export const generateScopeAndBenchmarks = async (inputs: BenchmarkInputs): Promise<ScopeAndBenchmarks> => {
  const ai = getAIClient();
  const prompt = `
    Based on the following benchmarking inputs, define the scope of analysis and suggest benchmarks.
    CRITICAL: Ensure the suggested benchmarks are highly relevant to the provided Business Problem and Goals.
    
    Business Problem: ${inputs.businessProblem}
    Current Context: ${inputs.currentContext}
    Goals: ${inputs.goals}
    
    Provide the output strictly adhering to the requested JSON schema.
  `;

  const response = await ai.models.generateContent({
    model: getModelName(),
    contents: prompt,
    config: {
      responseMimeType: 'application/json',
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          scope: {
            type: Type.OBJECT,
            properties: {
              targetFeature: { type: Type.STRING, description: 'The specific feature to analyze' },
              analyzedFlow: { type: Type.STRING, description: 'The user flow being analyzed' },
              impactedUser: { type: Type.STRING, description: 'The type of user impacted' },
              usageScenario: { type: Type.STRING, description: 'The scenario in which it is used' },
              testingMethod: { type: Type.STRING, description: 'How to test competitors (e.g., Sites, docs)' },
            },
            required: ['targetFeature', 'analyzedFlow', 'impactedUser', 'usageScenario', 'testingMethod']
          },
          benchmarks: {
            type: Type.OBJECT,
            properties: {
              direct: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Direct competitors (up to 3)' },
              market: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Market references (best in class)' },
              adjacent: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Adjacent products (SAAS, B2B, etc.)' },
            },
            required: ['direct', 'market', 'adjacent']
          }
        },
        required: ['scope', 'benchmarks']
      }
    }
  });

  return JSON.parse(response.text) as ScopeAndBenchmarks;
};

/**
 * Agent 3: Matrix Critic & Decision Agent (1-Pass Review Loop)
 * Audits the initial matrix generated by Agent 2 (Web Researcher) to ensure:
 * 1. Factual completeness and no empty/vague cells.
 * 2. Proper tag formatting ([FULL], [PARTIAL], [NONE]).
 * 3. Accurate comparison of "Our Product" against "What We Are Looking For".
 */
export const reviewAndRefineMatrix = async (
  rawMatrix: string,
  inputs: BenchmarkInputs,
  scopeData: ScopeAndBenchmarks,
  selectedBenchmarks: string[]
): Promise<{ refinedMatrix: string; criticSources: { title: string; uri: string }[] }> => {
  const ai = getAIClient();
  const competitorsToAnalyze = selectedBenchmarks.join(', ');

  const criticPrompt = `
    You are Agent 3: Matrix Critic & Executive Decision Agent.
    Your job is to audit, perform targeted live web searches for any missing competitor evidence, and refine the comparison matrix produced by Agent 2 (Web Researcher).

    Target Feature: "${scopeData.scope.targetFeature}"
    Business Problem: "${inputs.businessProblem}"
    Current Product Context: "${inputs.currentContext}"
    What We Are Looking For: "${inputs.goals}"
    Competitors: "${competitorsToAnalyze}"

    AGENT 1 INITIAL MATRIX DRAFT:
    ${rawMatrix}

    CRITIC AUDIT, SEARCH & REFINEMENT INSTRUCTIONS:
    1. TARGETED LIVE SEARCH FOR GAPS: If you detect any cell with vague, generic, or missing competitor capability evidence, perform a targeted live Google Search for that specific competitor and feature to find official documentation before finalizing the cell.
    2. REVIEW COMPLETENESS: Ensure every cell is clear, factual, and actionable. Replace any vague text with specific feature capabilities.
    3. ENFORCE TAG FORMATTING: Ensure EVERY data cell starts with exactly one status tag:
       - [FULL] for full/superior support
       - [PARTIAL] for partial/limited support
       - [NONE] for missing/unsupported feature
    4. OUR PRODUCT VALIDATION: Double check "Our Product" column. If a capability under "What We Are Looking For" is missing in "Current Product Context", tag Our Product as [NONE] or [PARTIAL].
    5. COLUMN HEADERS: Column 1 MUST be "Criterion", Column 2 MUST be "Our Product", followed by columns for each competitor (${competitorsToAnalyze}).
    6. Output ONLY the finalized, refined Markdown table. Plain text inside cells with the status tag prefix only.
  `;

  let criticSources: { title: string; uri: string }[] = [];

  try {
    const response = await ai.models.generateContent({
      model: getModelName(),
      contents: criticPrompt,
      config: {
        tools: [{ googleSearch: {} }],
        temperature: 0.1,
      }
    });

    const metadata = response.candidates?.[0]?.groundingMetadata;
    const chunks = metadata?.groundingChunks || [];
    criticSources = chunks
      .map(chunk => chunk.web)
      .filter((web): web is { uri: string; title: string } => web !== undefined && !!web.uri);

    if (response.text && response.text.includes('|')) {
      return { refinedMatrix: response.text.trim(), criticSources };
    }
  } catch (err) {
    console.warn('Agent 2 critic review fallback to raw matrix:', err);
  }

  return { refinedMatrix: rawMatrix, criticSources: [] };
};

export const generateMatrixWithSearch = async (
  inputs: BenchmarkInputs,
  scopeData: ScopeAndBenchmarks,
  selectedBenchmarks: string[],
  onStatusUpdate?: (status: string) => void
): Promise<MatrixResult> => {
  const ai = getAIClient();
  const competitorsToAnalyze = selectedBenchmarks.join(', ');
  
  if (onStatusUpdate) onStatusUpdate('Agent 1 (Web Researcher): Mining live web data...');

  const prompt = `
    MANDATORY REQUIREMENT: You MUST perform live Google searches for each of the selected competitors (${competitorsToAnalyze}) to find real, up-to-date evidence, features, official product pages, and documentation regarding: "${scopeData.scope.targetFeature}".

    Business Problem: ${inputs.businessProblem}
    Current Product Context: ${inputs.currentContext}
    What We Are Looking For (Goals & Desired Capabilities): ${inputs.goals}
    Target Feature: ${scopeData.scope.targetFeature}
    
    EXECUTIVE TABLE EVALUATION RULES:
    1. Output ONLY as a Markdown table.
    2. Columns MUST be: Criterion | Our Product | followed by one column for each selected competitor (${competitorsToAnalyze}).
    3. OUR PRODUCT EVALUATION: Compare "Current Product Context" against "What We Are Looking For". If a capability listed under "What We Are Looking For" is missing or only partially built in our current context, explicitly tag Our Product as [NONE] or [PARTIAL] for that criterion. Do NOT assume Our Product already has features we are looking to build!
    4. EXECUTIVE CONCISENESS: Each cell MUST begin with one of these status tags:
       - [FULL] for full/superior support
       - [PARTIAL] for partial/limited support
       - [NONE] for missing/unsupported feature
       Followed by a single concise bullet (MAX 20 words per cell). Be direct, factual, and scannable.
    5. CRITICAL: Do NOT use markdown formatting (like **bold**, *italics*) or HTML tags inside table cells. Plain text with the status tag prefix only.
  `;

  const response = await ai.models.generateContent({
    model: getModelName(),
    contents: prompt,
    config: {
      tools: [{ googleSearch: {} }],
      temperature: 0.2,
    }
  });

  const metadata = response.candidates?.[0]?.groundingMetadata;
  const chunks = metadata?.groundingChunks || [];
  let sources = chunks
    .map(chunk => chunk.web)
    .filter((web): web is { uri: string; title: string } => web !== undefined && !!web.uri);

  // If no direct groundingChunks were returned, extract web search queries or generate competitor search reference sources
  if (sources.length === 0) {
    const webQueries = (metadata as any)?.webSearchQueries || [];
    if (webQueries.length > 0) {
      sources = webQueries.map((q: string) => ({
        uri: `https://www.google.com/search?q=${encodeURIComponent(q)}`,
        title: `Google Search: ${q}`
      }));
    } else {
      sources = selectedBenchmarks.map(b => ({
        uri: `https://www.google.com/search?q=${encodeURIComponent(b + ' ' + scopeData.scope.targetFeature)}`,
        title: `${b} - ${scopeData.scope.targetFeature}`
      }));
    }
  }

  const rawMatrix = response.text || '';

  // Step 3B: Agent 3 1-Pass Review & Targeted Search Refinement Loop
  if (onStatusUpdate) onStatusUpdate('Agent 3 (Matrix Critic): Auditing precision & executing targeted searches...');
  const { refinedMatrix, criticSources } = await reviewAndRefineMatrix(rawMatrix, inputs, scopeData, selectedBenchmarks);

  // Combine and deduplicate sources from both Agent 1 (Initial Search) and Agent 2 (Targeted Refinement Search)
  const combinedSources = [...sources, ...criticSources];
  const uniqueSources = Array.from(new Map(combinedSources.map(item => [item.uri, item])).values());

  return {
    markdownTable: refinedMatrix,
    sources: uniqueSources
  };
};

export const generateSynthesis = async (matrixText: string, inputs: BenchmarkInputs): Promise<SynthesisResult> => {
  const ai = getAIClient();
  const prompt = `
    Based on the following comparison matrix and our original goals, perform a synthesis.
    
    Goals: ${inputs.goals}
    Matrix:
    ${matrixText}
    
    Provide the output strictly adhering to the requested JSON schema.
  `;

  const response = await ai.models.generateContent({
    model: getModelName(),
    contents: prompt,
    config: {
      responseMimeType: 'application/json',
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          swot: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                competitor: { type: Type.STRING },
                strengths: { type: Type.ARRAY, items: { type: Type.STRING } },
                weaknesses: { type: Type.ARRAY, items: { type: Type.STRING } },
                reuse: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'What we can reuse/learn' },
                avoid: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'What we should avoid' }
              },
              required: ['competitor', 'strengths', 'weaknesses', 'reuse', 'avoid']
            }
          },
          gaps: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                need: { type: Type.STRING, description: 'Business need' },
                gap: { type: Type.STRING, description: 'Identified gap in our product' },
                opportunity: { type: Type.STRING, description: 'Opportunity for improvement' }
              },
              required: ['need', 'gap', 'opportunity']
            }
          },
          prioritization: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                item: { type: Type.STRING, description: 'Feature or improvement' },
                priority: { type: Type.STRING, description: 'Must Have, Should Have, Could Have, or Won\'t Have' },
                reason: { type: Type.STRING }
              },
              required: ['item', 'priority', 'reason']
            }
          }
        },
        required: ['swot', 'gaps', 'prioritization']
      }
    }
  });

  return JSON.parse(response.text) as SynthesisResult;
};

export const generateFinalReport = async (
  inputs: BenchmarkInputs,
  scope: ScopeAndBenchmarks,
  synthesis: SynthesisResult
): Promise<string> => {
  const ai = getAIClient();
  const prompt = `
    You are Agent 5: Executive Tech Writer & Lead Product Manager.
    Generate a complete, highly structured Executive Recommendation Report and User Stories adhering MANDATORILY to the official Report System Design Specification.

    INPUT DATA:
    - Business Problem: ${inputs.businessProblem}
    - Current Product Context: ${inputs.currentContext}
    - Goals / Desired Outcome: ${inputs.goals}
    - Target Feature: ${scope.scope.targetFeature}
    - Strategic Synthesis (SWOT & Prioritization): ${JSON.stringify(synthesis)}

    CRITICAL FEATURE RELEVANCE INSTRUCTION:
    All content (Bottlenecks, Strategic Capabilities, Prioritized Features, Rollout Phases, and User Stories) MUST BE 100% SPECIFIC TO THE TARGET FEATURE ("${scope.scope.targetFeature}") and GOALS ("${inputs.goals}"). Do NOT invent unrelated email or notification features unless the target feature is explicitly about notifications!

    MANDATORY REPORT STRUCTURE & PRESENTATION SPECIFICATION:

    # Executive Benchmarking & Recommendation Report
    *Official Product Analysis & Feature System Specification*

    ## 1. Executive Summary

    > Executive Summary: Write a high-impact, single-paragraph executive summary detailing the strategic necessity of "${scope.scope.targetFeature}", how it eliminates current operational friction, accelerates remediation/adoption, and aligns with business goals.

    ## 2. Key Gaps & Strategic Opportunities

    ### Current State Bottlenecks
    **Bold Title Prefix:** Detailed description of current workflow friction or operational limitation related to "${scope.scope.targetFeature}".
    **Bold Title Prefix:** Detailed description of security, usability, or adoption delays.
    **Bold Title Prefix:** Detailed description of manual effort or user assistance overhead.

    ### Strategic Capabilities
    **Bold Title Prefix:** Strategic description of the key capability for "${scope.scope.targetFeature}".
    **Bold Title Prefix:** Strategic description of 1-click actionability, direct interface, or automation.
    **Bold Title Prefix:** Strategic description of targeted customization, preference, or governance.

    ## 3. Recommendations & Phased Implementation Roadmap

    ### Prioritized Feature Matrix
    | Feature Module | Priority | Strategic Value |
    |---|---|---|
    | **[Name of High Priority Feature Module]** | 🔴 Must Have | Explanation of strategic value and immediate gap resolution. |
    | **[Name of Core Secondary Feature Module]** | 🔴 Must Have | Explanation of how it dramatically lowers friction-to-action. |
    | **[Name of Management/Setting Feature Module]** | 🟡 Should Have | Explanation of how it prevents friction and ensures usability. |
    | **[Name of Advance/Predictive Feature Module]** | 🔵 Could Have | Explanation of how it enhances predictability for operations. |

    ### Phased Rollout Plan
    ### Phase 1: Foundation & Core Functionality (Sprint 1–2)
    - Implement baseline MVP architecture and core user interaction for "${scope.scope.targetFeature}".
    - Deliver foundational workflows and primary user interface elements.
    - Embed authenticated core data models and essential triggers.

    ### Phase 2: Customization & Governance (Sprint 3–4)
    - Introduce user settings, preferences, and configuration controls.
    - Support Role-Based Access Control (RBAC), filtering, or accessibility options.
    - Provide audit logging, analytics, and operational monitoring for the feature.

    ### Phase 3: Advanced Intelligence & Automation (Sprint 5–6)
    - Build advance warning, proactive automation, or predictive intelligence engine.
    - Implement automated routines and proactive reminders.
    - Enable preview and customization of advanced enterprise controls.

    ## 4. Actionable User Stories & Acceptance Criteria

    ### User Story 1: [Feature Module 1 Title]
    **As an** [Target User Persona],
    **I want to** [action/capability related to ${scope.scope.targetFeature}],
    **So that** [business benefit/outcome].

    **MoSCoW Priority:** 🔴 Must Have

    **Acceptance Criteria:**
    - The system MUST automatically execute [primary capability] within [timeframe/trigger].
    - The interface MUST display [key parameters/information].
    - The platform MUST validate [data/rule] to prevent duplicate or invalid actions.

    ### User Story 2: [Feature Module 2 Title]
    **As an** [Target User Persona],
    **I want to** [action/capability related to ${scope.scope.targetFeature}],
    **So that** [business benefit/outcome].

    **MoSCoW Priority:** 🔴 Must Have

    **Acceptance Criteria:**
    - The system MUST provide [UI element/CTA] for [action].
    - Clicking/triggering the action MUST direct the user to [target state/dashboard].
    - If unauthenticated, the system MUST redirect to login and return to target state upon authentication.

    ### User Story 3: [Feature Module 3 Title]
    **As an** [Target User Persona],
    **I want to** [action/capability related to ${scope.scope.targetFeature}],
    **So that** [business benefit/outcome].

    **MoSCoW Priority:** 🟡 Should Have

    **Acceptance Criteria:**
    - The platform MUST provide a configuration/preferences page for [Feature].
    - Admins MUST be able to customize [settings/roles/filters].
    - Users MUST be able to toggle preference settings between options.

    ### User Story 4: [Feature Module 4 Title]
    **As an** [Target User Persona],
    **I want to** [action/capability related to ${scope.scope.targetFeature}],
    **So that** [business benefit/outcome].

    **MoSCoW Priority:** 🔵 Could Have

    **Acceptance Criteria:**
    - System Admins MUST be able to configure advance thresholds or automated schedules.
    - The system MUST send/trigger automated routines containing planned updates.
    - The system MUST provide an option to pause or reschedule automated actions.

    CRITICAL RULES:
    1. Do NOT alter these section titles or H1/H2/H3 headings.
    2. ALWAYS format **As an**, **I want to**, **So that**, **MoSCoW Priority:**, and **Acceptance Criteria:** in bold.
    3. ALWAYS use direct color icons (🔴, 🟡, 🔵, ⚪) for MoSCoW priorities.
    4. Keep the Phased Rollout Plan strictly vertical line-by-line.
    5. Output ONLY clean Markdown matching this exact structure.
  `;

  const response = await ai.models.generateContent({
    model: getModelName(),
    contents: prompt,
    config: {
      temperature: 0.2,
    }
  });

  return response.text || '';
};
